"""create_intake_table

Revision ID: 38f7b4d7da79
Revises: b116158bd7a3
Create Date: 2026-08-17 07:24:08.809467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f7b4d7da79'
down_revision: Union[str, Sequence[str], None] = 'b116158bd7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intakes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lab_id', sa.Uuid(), nullable=False),
    sa.Column('lab_sequence', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('patient_name', sa.String(length=150), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('patient_gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('patient_address', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'STAT', name='priorityenum'), nullable=False),
    sa.Column('referring_doctor', sa.String(length=150), nullable=True),
    sa.Column('clinical_notes', sa.String(length=1000), nullable=True),
    sa.Column('intake_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_collection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'SAMPLE_COLLECTED', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='intakestatusenum'), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIAL', 'PAID', 'REFUNDED', name='paymentstatusenum'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'INSURANCE', 'NONE', name='paymentmethodenum'), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FLAT', 'NONE', name='discounttypeenum'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('test_ids', sa.JSON().with_variant(sa.JSON(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'accession_number', name='uq_lab_accession')
    )
    op.create_index(op.f('ix_intakes_accession_number'), 'intakes', ['accession_number'], unique=False)
    op.create_index(op.f('ix_intakes_id'), 'intakes', ['id'], unique=False)
    op.create_index(op.f('ix_intakes_lab_id'), 'intakes', ['lab_id'], unique=False)
    op.create_index(op.f('ix_intakes_patient_phone'), 'intakes', ['patient_phone'], unique=False)
    op.create_index(op.f('ix_intakes_referring_doctor'), 'intakes', ['referring_doctor'], unique=False)
    op.create_index(op.f('ix_intakes_status'), 'intakes', ['status'], unique=False)
    op.create_index('ix_lab_intake_date', 'intakes', ['lab_id', 'intake_date'], unique=False)
    op.create_index('ix_lab_patient_phone', 'intakes', ['lab_id', 'patient_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lab_patient_phone', table_name='intakes')
    op.drop_index('ix_lab_intake_date', table_name='intakes')
    op.drop_index(op.f('ix_intakes_status'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_referring_doctor'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_patient_phone'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_lab_id'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_id'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_accession_number'), table_name='intakes')
    op.drop_table('intakes')
    # ### end Alembic commands ###
