"""initial_schema

Revision ID: b116158bd7a3
Revises: 
Create Date: 2026-08-08 23:44:12.267229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b116158bd7a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('report_header_text', sa.String(length=500), nullable=True),
    sa.Column('report_footer_text', sa.Text(), nullable=True),
    sa.Column('director_name', sa.String(length=150), nullable=True),
    sa.Column('director_signature_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_lab_owner_id', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_id'), 'labs', ['id'], unique=False)
    op.create_index(op.f('ix_labs_owner_id'), 'labs', ['owner_id'], unique=True)
    op.create_table('master_catalog_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loinc_code', sa.String(), nullable=True),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('HEMATOLOGY', 'CLINICAL_BIOCHEMISTRY', 'ENDOCRINOLOGY', 'IMMUNOLOGY_SEROLOGY', 'CLINICAL_PATHOLOGY', 'MICROBIOLOGY', 'HISTOPATHOLOGY_CYTOLOGY', 'TUMOR_MARKERS', name='departmentenum', native_enum=False), nullable=False),
    sa.Column('sample_type', sa.Enum('WHOLE_BLOOD_EDTA', 'SERUM_SST', 'PLASMA_FLUORIDE', 'PLASMA_CITRATE', 'URINE_MID_STREAM', 'URINE_24_HRS', 'STOOL', 'SPUTUM', 'SEMEN', 'TISSUE_SWAB', 'BODY_FLUID', 'CSF', name='sampletypeenum', native_enum=False), nullable=False),
    sa.Column('default_tat', sa.String(), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pdf_result_fields', sa.JSON(), nullable=True),
    sa.Column('clinical_guidelines', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_catalog_tests_id'), 'master_catalog_tests', ['id'], unique=False)
    op.create_index(op.f('ix_master_catalog_tests_loinc_code'), 'master_catalog_tests', ['loinc_code'], unique=True)
    op.create_index(op.f('ix_master_catalog_tests_official_name'), 'master_catalog_tests', ['official_name'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lab_id', sa.Uuid(), nullable=False),
    sa.Column('master_test_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('HEMATOLOGY', 'CLINICAL_BIOCHEMISTRY', 'ENDOCRINOLOGY', 'IMMUNOLOGY_SEROLOGY', 'CLINICAL_PATHOLOGY', 'MICROBIOLOGY', 'HISTOPATHOLOGY_CYTOLOGY', 'TUMOR_MARKERS', name='departmentenum', native_enum=False), nullable=False),
    sa.Column('sample_type', sa.Enum('WHOLE_BLOOD_EDTA', 'SERUM_SST', 'PLASMA_FLUORIDE', 'PLASMA_CITRATE', 'URINE_MID_STREAM', 'URINE_24_HRS', 'STOOL', 'SPUTUM', 'SEMEN', 'TISSUE_SWAB', 'BODY_FLUID', 'CSF', name='sampletypeenum', native_enum=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tat', sa.String(), nullable=False),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_test_id'], ['master_catalog_tests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'code', name='uix_lab_id_test_code')
    )
    op.create_index(op.f('ix_lab_tests_id'), 'lab_tests', ['id'], unique=False)
    op.create_index(op.f('ix_lab_tests_is_active'), 'lab_tests', ['is_active'], unique=False)
    op.create_index(op.f('ix_lab_tests_lab_id'), 'lab_tests', ['lab_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('default_lab_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_lab_id'], ['labs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_table('lab_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lab_id', sa.Uuid(), nullable=False),
    sa.Column('permissions', sa.JSON(), server_default='["read_only"]', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='membershipstatus', native_enum=False), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lab_id', name='uix_user_lab')
    )
    op.create_index(op.f('ix_lab_memberships_id'), 'lab_memberships', ['id'], unique=False)
    op.create_index('ix_user_lab_lookup', 'lab_memberships', ['user_id', 'lab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_lab_lookup', table_name='lab_memberships')
    op.drop_index(op.f('ix_lab_memberships_id'), table_name='lab_memberships')
    op.drop_table('lab_memberships')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lab_tests_lab_id'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_is_active'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_master_catalog_tests_official_name'), table_name='master_catalog_tests')
    op.drop_index(op.f('ix_master_catalog_tests_loinc_code'), table_name='master_catalog_tests')
    op.drop_index(op.f('ix_master_catalog_tests_id'), table_name='master_catalog_tests')
    op.drop_table('master_catalog_tests')
    op.drop_index(op.f('ix_labs_owner_id'), table_name='labs')
    op.drop_index(op.f('ix_labs_id'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
